spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification
      username: root
      password: root
      authentication-database: admin
server:
  port: 8081
